### ISSUE TITLE
How to get new change value?

### ISSUE THREAD

**Issue by coldes** [tigrr/drum#1]
Hello - How do I get new change value after scroll? I can get an initial value, not sure how to call the change event

````
//onload initial value
var initial = $(".drum").attr("aria-valuenow");
console.log("valuenow: " + initial);
$("#drumvalue").text("valuenow: " + initial);

//change: Triggers when the drum has finished revolving and we have a new value
//HOW TO TRIGGER?
$(".drum").on("change", function() {
	//$(".drum-item").change(function(){
	//$(".drum-viewport").on("change", ".drum", function(){
	//console.log(this.value);

	var valuenow = $('.drum').attr('aria-valuenow');

	console.log('valuechanged: '+ valuenow);
	$('#drumvalue').text('valuechanged: '+ valuenow);
});
````
[https://cdpn.io/coldes/debug/2a377658222b322995050554712968c8](url)

Can you assist?  - thank you

**Comment by tigrr** [comment]
Hello,

You can listen for change event by passing a callback at the initialization:
```
$(".drum").drum({
	min: 40,
	max: 240,
	value: 1,
	step: 2,
	orderAsc: false,
	change: function(event, data) {
		var valuenow = data.value;
		console.log('valuechanged: '+ valuenow);
		$('#drumvalue').text('valuechanged: '+ valuenow);
	}
});
```
or attach a listener to the `drumchange` event at a later point:
```
$(".drum").on('drumchange', function(event, data) {
	var valuenow = data.value;
	console.log('valuechanged: '+ valuenow);
	$('#drumvalue').text('valuechanged: '+ valuenow);
});
```

Notice how in both cases the callback receives `data` object with the new `value`.

Also, to get the value at any time, use `value` method:
`$('.drum').drum('value');`
or `value` option:
`$('.drum').drum('option', 'value');`
You can set the value by passing second (or third for the option variant) argument:
`$('.drum').drum('value', 70);`

All this is in accordance with standard jQuery widget behavior. For details see the [jQuery widget docs](https://api.jqueryui.com/jQuery.widget/).

I understand this may be unclear to many users, so I will update the plugin documentation.
Thank you for bringing it to my attention.

**Comment by coldes** [comment]
...excellent, many thanks
